add basic bearer auth
HardSign-Team/eventnet-backend pull request #1
Opened 2022-03-08 14:22 UTC by DaGnYMilleR

2022-03-08 17:30 UTC, gODeaLoAple requested changes
В целом хуево. В контур не проходишь.

2022-03-08 17:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/WeatherForecastController.cs
> +using Eventnet.Models;
Этот файл вроде надо удалить

2022-03-08 17:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Models/JwtAuthResult.cs
> +    public JwtSecurityToken AccessToken { get; init; }
Не знаю, есть ли в этом смысл. Но имеет смысле использовать nullable-подсказки. В данном случае либо пометить ? это проперти, либо добавить конструктор, либо использовать рекорды.  (Json-сериализаторы умеют парсить и сериализовывать с помощью него)

Стоит отметить, что у рекордов есть одна интересная особенность: если ты хочешь навесить аттрибут на проперти, которое генерируется, то нужно в аттрибуте указать параметр property.


`
 public record JwtAuthResult([property: JsonPropertyName("accessToken")] JwtSecurityToken AccessToken)
`

2022-03-08 17:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Models/JwtAuthResult.cs
> +    public JwtSecurityToken AccessToken { get; init; }
Не знаю, есть ли в этом смысл. Но имеет смысле использовать nullable-подсказки. В данном случае либо пометить ? это проперти, либо добавить конструктор. (Json-сериализаторы умеют парсить и сериализовывать с помощью него)

2022-03-08 17:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Models/JwtTokenConfig.cs
> +﻿namespace Eventnet.Models;
См. примечание выше.

2022-03-08 17:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Models/JwtTokenConfig.cs
> +﻿namespace Eventnet.Models;
См. примечание выше.

2022-03-08 17:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Models/LoginModel.cs
> +﻿using System.ComponentModel.DataAnnotations;
См. примечание к другим моделям.

2022-03-08 17:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Models/LoginModel.cs
> +﻿using System.ComponentModel.DataAnnotations;
См. примечание к другим моделям.

2022-03-08 17:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Models/LoginResponseModel.cs
> +﻿using Eventnet.DataAccess;
См. примечание к другим моделям.

2022-03-08 17:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Models/LoginResponseModel.cs
> +﻿using Eventnet.DataAccess;
См. примечание к другим моделям.

2022-03-08 17:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Models/RegisterModel.cs
> +﻿using System.ComponentModel.DataAnnotations;
См. примечание к другим моделям.

2022-03-08 17:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Models/RegisterModel.cs
> +﻿using System.ComponentModel.DataAnnotations;
См. примечание к другим моделям.

2022-03-08 17:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Models/RegisterModel.cs
> +    public string Username { get; set; }
Почему и зачем так много сеттеров?

2022-03-08 17:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Models/RegisterModel.cs
> +    public string Username { get; set; }
Почему и зачем так много сеттеров?

2022-03-08 17:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Models/UserRoles.cs
> +    public const string Admin = nameof(Admin);
Не думаю, что это хорошее решение. Вернее, есть очень маленькая проблема, которая вряд ли случится, но выскажу такую мысль. При редактировании поля ты поменяшь значение этого поля и можешь этого не заметить. Например

`Admin => SuperAdmin`



Соответственно, если ты это значение еще где-то хранишь в бд, то останется старое значение. Таким образом все админы потеряют роль админов.

В данном случае я бы просто вставил константное значене, не зависящее от название поля через nameof, typeof и т.д.

2022-03-08 17:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Models/UserRoles.cs
> +    public const string Admin = nameof(Admin);
Не думаю, что это хорошее решение. Вернее, есть очень маленькая проблема, которая вряд ли случится, но выскажу такую мысль. При редактировании поля ты поменяшь значение этого поля и можешь этого не заметить. Например

`Admin => SuperAdmin`



Соответственно, если ты это значение еще где-то хранишь в бд, то останется старое значение. Таким образом все админы потеряют роль админов.

В данном случае я бы просто вставил константное значене, не зависящее от название поля через nameof, typeof и т.д.

2022-03-08 17:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Models/WeatherForecast.cs
> +namespace Eventnet.Models;
Удалить.

2022-03-08 17:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Models/WeatherForecast.cs
> +namespace Eventnet.Models;
Удалить.

2022-03-08 17:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/appsettings.json
> +    "DefaultConnection": "Server=127.0.0.1;Port=5432;Database=eventnet;User Id=postgres;Password=1234;"
Я бы положил это в environment. Стоит обсудить.

2022-03-08 17:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/appsettings.json
> +    "DefaultConnection": "Server=127.0.0.1;Port=5432;Database=eventnet;User Id=postgres;Password=1234;"
Я бы положил это в environment. Стоит обсудить.

2022-03-08 17:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/appsettings.json
> +    "Secret": "ByYM000OLlMQG6VVVp1OH7Xzyr7gHuw1qvUC5dcGt3SNM",
Я бы положил это в environment. Стоит обсудить.

2022-03-08 17:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/appsettings.json
> +    "Secret": "ByYM000OLlMQG6VVVp1OH7Xzyr7gHuw1qvUC5dcGt3SNM",
Я бы положил это в environment. Стоит обсудить.

2022-03-08 17:31 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/WeatherForecastController.cs
> +using Eventnet.Models;
Это тестовый контроллер, чтобы можно было проверить работу, когда появится настоящий - удалим

2022-03-08 18:07 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Models/WeatherForecast.cs
> +namespace Eventnet.Models;
См. примечание выше.

2022-03-08 18:09 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Models/UserRoles.cs
> +    public const string Admin = nameof(Admin);
Ты описал какой-то слишком вакуумный случай, как мне кажется.

2022-03-09 04:09 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Models/JwtAuthResult.cs
> +    public JwtSecurityToken AccessToken { get; init; }
Это проперти не нужно(
Предлагаю обсудить, как мы работаем с nullable типами в целом

2022-03-09 04:12 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/WeatherForecastController.cs
> +using Eventnet.Models;
Этот файл вроде надо удалить

2022-03-09 04:12 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Models/JwtAuthResult.cs
> +public record JwtAuthResult(JwtSecurityToken AccessToken);
А разве у этого объекта в json поле не должно быть с маленькой буквы? Или это автоматически делается?

2022-03-09 04:12 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Models/LoginModel.cs
> +public record LoginModel(
Почему убрал мессаджи?

2022-03-09 04:13 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/WeatherForecastController.cs
> +using Eventnet.Models;
Так он удален жи

2022-03-09 04:14 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/WeatherForecastController.cs
> +using Eventnet.Models;
Не знаю, почему, но это осталось с прошлого ревью.

2022-03-09 04:14 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Models/JwtAuthResult.cs
> +public record JwtAuthResult(JwtSecurityToken AccessToken);
Ну это проперти, но я немного переделал и теперь этот обьект вообще не нуждается в сериализации

2022-03-09 04:15 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Models/LoginModel.cs
> +public record LoginModel(
Потому что by default ставится мессадж "FieldName field is requierd", что меня вполне устраивает

2022-03-09 04:32 UTC, gODeaLoAple approved these changes

2022-03-09 05:10 UTC, merged