Marks (aka Likes and Dislikes)
HardSign-Team/eventnet-backend pull request #12
Opened 2022-04-23 18:16 UTC by gODeaLoAple

2022-04-24 11:00 UTC, DaGnYMilleR requested changes

2022-04-24 11:00 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/MarksController.cs
> +    [HttpPost("likes/add/{eventId:guid}")]
А для чего ты используешь add/remove? Разве хттпшных POST, DELETE недостаточно?

2022-04-24 11:00 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/MarksController.cs
> +        var user = await currentUserService.GetCurrentUser() ?? throw new Exception();
Просто Exception? Предлагаю добавить конкретики в текст/кидать 401

2022-04-24 11:00 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/MarksController.cs
> +    private async Task<IActionResult> CountMarks(Guid eventId)
Можно добавить ко всем методам эндпоинтов [Produces], чтобы в сваггере было понятно, что за моделька возвращается

2022-04-24 11:00 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +using Eventnet.Api.Models.Marks;
Общий коммент. Не замечаете, как у нас контроллер с евентами начал очень сильно разрастаться? Тут и конфиг для пэйджинга и допустимые форматы файлов и конфиг кролика. Предлагаю сделать чето с этим)

2022-04-24 11:00 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Helpers/MarksQueryExtensions.cs
> +public static class MarksQueryExtensions
Точно ли этому место в Application layer? Мб логичней где-то рядом с самой сущностью. Мы на работе, например, тоже пишем такие экстеншны вместо репозиториев(даже хоткеи для их генерации есть), и складываем их в один файл с самой Entity

2022-04-24 11:00 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Services/SaveServices/BackgroundConsumeEventService.cs
> +    public BackgroundConsumeEventService(
Неймспейс говна почему-то
Во всех остальных файлах из этой папки тоже

2022-04-24 11:00 UTC, DaGnYMilleR commented on Eventnet/Eventnet.DataAccess/Entities/EventEntity.cs
> +
![image](https://user-images.githubusercontent.com/37438377/164973080-62263c55-9fb7-48eb-aa11-1b8e216e1514.png)
Мы туда не добавляем ничего что-ли? Или у нас засчет этих "фабрик", оценки сами добавятся в этот список?

2022-04-24 11:19 UTC, gODeaLoAple commented on Eventnet/Eventnet.DataAccess/Entities/EventEntity.cs
> +
По идее, надо сделать ридонли коллекцию, потому что добавление происходит за счет добавление в DbSet<MarkEntity> с указанием ссылки на EventEntity.
А это свойство нужно только для легкого доступа ко всем оценкам (например, чтобы сделать .Count()).

2022-04-24 11:19 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Helpers/MarksQueryExtensions.cs
> +public static class MarksQueryExtensions
Имеет место быть

2022-04-24 11:20 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/MarksController.cs
> +    [HttpPost("likes/add/{eventId:guid}")]
Ну, кажется, что для лайков странно использовать DELETE-метод.

2022-04-24 11:41 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +using Eventnet.Api.Models.Marks;
![image](https://user-images.githubusercontent.com/55148949/164974722-f8736217-1a09-4743-a4d0-11bf5fa4ac01.png)

2022-04-24 11:50 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/MarksController.cs
> +    [HttpPost("likes/add/{eventId:guid}")]
Вообще, лайки по идее связаны с евентом, это к тому, что почему бы не events/{id}/likes (но это похер на самом деле)
Ну мы ведь удаляем лайки из базы, так почему бы и не DELETE? В общем, почему тебе кажется, что это странно?

2022-04-24 11:52 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/MarksController.cs
> +        var user = await currentUserService.GetCurrentUser();
Мы сначала чекаем на то что событие существует, а только потом на то что юзер существует. Кажется, что должно быть наоборот, так как если нет пользователя, то мы не хотим отдавать инфу о существовании/несуществовании события

2022-04-24 11:52 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/MarksController.cs
> +    [HttpPost("likes/add/{eventId:guid}")]
По поводу ивента тоже думал. Можно было бы и подписки туда вынести, но я подумал, что тогда будет слишком много endpoints на один контроллер. Или все же стоит их поместить в ивент?

В принципе, резонно, перепишу.

2022-04-24 11:56 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/MarksController.cs
> +    [HttpPost("likes/add/{eventId:guid}")]
Наверное, для подписок та же логика верна.

2022-04-25 17:13 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/MarksController.cs
> +        var user = await currentUserService.GetCurrentUser();
Неавторизованные пользователи имеют доступ к событиям... Они просто не могут выполнять некоторые действия с ним. Но проверку подвину, наверное, чтобы более четко разделить проверки.

2022-04-25 18:02 UTC, DaGnYMilleR approved these changes

2022-04-25 18:07 UTC, IvanSibirtsev approved these changes

2022-04-25 18:28 UTC, merged