Implement get event by id method
HardSign-Team/eventnet-backend pull request #2
Opened 2022-03-10 16:45 UTC by gODeaLoAple

Имплементировал пока только один метод. Решил почаще кидать пул реквесты, чтобы не потратить уйму времени зря и учесть ошибки из предыдущего этапа, на которые вы можете мне указать.

2022-03-10 17:41 UTC, DaGnYMilleR requested changes
Писать заглушки - кринж!

2022-03-10 17:41 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api.Tests/EventControllerTests/GetEventByIdShould.cs
> +        response.StatusCode.Should().Be(HttpStatusCode.NotFound);
точно ли NotFound когда передали даже не Guid?

2022-03-10 17:41 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api.Tests/Helpers/Utilities.cs
> +    public static void InitializeDbForTests(ApplicationDbContext db)
Method 'InitializeDbForTests' can be made private

2022-03-10 17:41 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api.Tests/TestWebApplicationFactory.cs
> +            var db = scopedServices.GetRequiredService<ApplicationDbContext>();
DbContext вроде IDisposable. Но, возможно, scope сам может управлять этим

2022-03-10 17:41 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api.Tests/TestsBase.cs
> +    protected void ApplyToDb(Action<ApplicationDbContext> action)
Method 'ApplyToDb' is never used

2022-03-10 17:41 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api.Tests/TestsBase.cs
> +        using var scope = scopeFactory!.CreateScope();
Те кто пишет !! не познали дао котлина

2022-03-10 17:41 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Models/CreateEventModel.cs
> +public record CreateEventModel(
nrt имплиситно вкдючает в себя required
https://docs.microsoft.com/en-us/ef/core/modeling/entity-properties?tabs=data-annotations%2Cwithout-nrt#required-and-optional-properties

2022-03-10 18:21 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +    public IActionResult GetEventById(Guid eventId)
А почему ты не навесил [Authorize], думаю, что тестировать надо с учетом этого, т.е. перед началом тестов создавать юзера, ходить в логин и получать токен

2022-03-10 18:22 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +    public IActionResult GetEventById(Guid eventId)
Для просмотра ивентов необязательно быть авторизованным. Вообще говоря, надо это обсудить чуть позже с остальными.

2022-03-10 18:24 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +    [HttpPost]
Post?

2022-03-10 18:25 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +    [HttpPost]
Get же не имеет тела, а мне нужно фильтры принять.

2022-03-10 18:27 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +    [HttpPatch("{eventId:guid}")]
Patch же вроде как реализуется при помощи специального формата...
https://datatracker.ietf.org/doc/html/rfc6902

2022-03-10 18:32 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +    [HttpPatch("{eventId:guid}")]
Ну да, надо заменить. Перепутал с Put.

2022-03-10 18:36 UTC, DaGnYMilleR commented on Eventnet/Eventnet.DataAccess/ApplicationDbContext.cs
>  public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
А чо ApplicationUser в ApplicationUserEntity не переименовал? Можно даже просто User и UserEntity сделать наверн

2022-03-10 19:19 UTC, gODeaLoAple commented on Eventnet/Eventnet.DataAccess/ApplicationDbContext.cs
>  public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
Боялся, что из-за переименования какие-нибудь конвенции нарушить и сломать все к чертям. Переименую, посмотрим.

2022-03-10 19:20 UTC, DaGnYMilleR commented on Eventnet/Eventnet.DataAccess/ApplicationDbContext.cs
>  public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
Be brave!

2022-03-12 17:20 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api.Tests/EventControllerTests/GetEventByIdShould.cs
> +        response.StatusCode.Should().Be(HttpStatusCode.NotFound);
Почему-то по-умолчанию в таком случае параметр рассматривается как продложение метода, а не как параметр, а т.к. контроллер /api/events/smth не реализован, автмоатичски получается not found.

2022-03-12 17:28 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api.Tests/TestWebApplicationFactory.cs
> +            var db = scopedServices.GetRequiredService<ApplicationDbContext>();
Тут аутофак, но ставлю на то, что стандартный DI-Container обладает таким же поведением скопов:
https://csharp.christiannagel.com/2018/08/29/scopes/

2022-03-13 06:51 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Helpers/PagedListExtensions.cs
> +public static class PagedListExtensions3
А где 1 и 2?

2022-03-13 09:53 UTC, DaGnYMilleR approved these changes

2022-03-13 09:55 UTC, lapakota commented
Идеально

2022-03-13 09:56 UTC, lapakota approved these changes
Топ

2022-03-13 09:56 UTC, merged