Update event
HardSign-Team/eventnet-backend pull request #28
Opened 2022-05-25 15:49 UTC by IvanSibirtsev

2022-05-25 16:34 UTC, DaGnYMilleR requested changes

2022-05-25 16:34 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +        if (!ModelState.IsValid)
это лучше в самом начале метода делать

2022-05-25 16:34 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +        {
{

2022-05-25 16:34 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +        }
}

2022-05-25 16:34 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +        {
{

2022-05-25 16:34 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +        }
}

2022-05-25 16:34 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Models/Events/UpdateEventModel.cs
> +    [Required] [Range(-90, 90)] double Longitude,
а почему -90, 90? я реально не в курсе...

2022-05-25 16:34 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Infrastructure/EventEventSaveToDbService.cs
> +            oldValue.Description = eventInfo.Description;
мне дико лень скролить вверх, но у нас же Update реализован через Patch, а тут ты прям все свойства сетишь, получается Put какой-то или я чето не понимаю?

2022-05-25 16:34 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Infrastructure/PhotoServices/PhotoStorageService.cs
> +        //    throw new DirectoryNotFoundException($"Directory {config.Path} not found");
nc

2022-05-25 16:38 UTC, IvanSibirtsev commented on Eventnet/Eventnet.Infrastructure/PhotoServices/PhotoStorageService.cs
> +        //    throw new DirectoryNotFoundException($"Directory {config.Path} not found");
а я щитаю что это в назидание

2022-05-25 16:41 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Infrastructure/PhotoServices/PhotoStorageService.cs
> +        //    throw new DirectoryNotFoundException($"Directory {config.Path} not found");
можно не чекать на существование btw
https://stackoverflow.com/questions/9065598/if-a-folder-does-not-exist-create-it

2022-05-25 16:51 UTC, IvanSibirtsev commented on Eventnet/Eventnet.Api/Models/Events/UpdateEventModel.cs
> +    [Required] [Range(-90, 90)] double Longitude,
![image](https://user-images.githubusercontent.com/58268658/170317174-c5ad89d7-9435-4d19-8d44-87600a20efdc.png)
ну не будет у нас ивентов в Иркутске и чё

2022-05-25 16:52 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Models/Events/UpdateEventModel.cs
> +    [Required] [Range(-90, 90)] double Longitude,
no Ircutsck - no approve

2022-05-25 18:22 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Models/Events/UpdateEventModel.cs
> +    [Required] [Range(-90, 90)] double Longitude,
Всмы, а че, не от 90 до 90?

2022-05-26 09:37 UTC, gODeaLoAple approved these changes

2022-05-26 09:37 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api.IntegrationTests/Mocks/ConsumeSaveEventMock.cs
> +}
А почему ты не пользуешься Mock<IConsumeSaveEventService>? Он сделает то же самое вроде как

2022-05-26 09:37 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Models/Events/UpdateEventModel.cs
> +    [Required] [Range(-90, 90)] double Longitude,
Если нетрудно, то поменяй на
Latitude in [-90, 90]
Longitude in [-180, 180]

2022-05-26 09:37 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Properties/launchSettings.json
> +      "launchBrowser": false,
А че так?

2022-05-26 09:37 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Services/SaveServices/EventPublisher.cs
> +            channel.BasicPublish("", queue, null, Encoding.UTF8.GetBytes(message));
😵‍💫

2022-05-26 09:40 UTC, IvanSibirtsev commented on Eventnet/Eventnet.Api.IntegrationTests/Mocks/ConsumeSaveEventMock.cs
> +}
а я вообще не пользуюсь. просто сигнатуру поменял

2022-05-29 07:24 UTC, merged