Auth
HardSign-Team/eventnet-backend pull request #3
Opened 2022-03-13 09:52 UTC by DaGnYMilleR

2022-03-13 12:40 UTC, IvanSibirtsev requested changes
В целом отлично. В контур проходишь.

2022-03-13 12:40 UTC, IvanSibirtsev commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +            "jopa",
ok

2022-03-13 12:40 UTC, IvanSibirtsev commented on Eventnet/Eventnet.Api.Tests/JwtAuthService_Should.cs
> +        var tokens1 = sut.GenerateTokens(userName, claims, now);
можно же задеконстрактить

2022-03-13 13:08 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api.Tests/JwtAuthService_Should.cs
> +        Secret = "I see a red door and I want it painted black"
I see a dangeoun and I want to swallow cum

2022-03-13 14:30 UTC, gODeaLoAple requested changes
Среди ублюдков шел master, в dark dangeon, пьяный анархист
Крикнул он: "ХОЙ!!! 
anal ДОЛОЙ!!!"
Slaves вел он за собой

2022-03-13 14:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api.Tests/Eventnet.Api.Tests.csproj
> +<Project Sdk="Microsoft.NET.Sdk">
Думаю, можно переименовать в UnitTests

2022-03-13 14:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api.Tests/JwtAuthService_Should.cs
> +public class JwtAuthService_Should
Я написал больше тестов, так что используем стиль нейминга без _ :)

2022-03-13 14:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Infrastructure/EmailConfiguration.cs
> +﻿namespace Eventnet.Infrastructure;
![image](https://user-images.githubusercontent.com/55148949/158063144-812c8741-461a-4b3c-961a-10e0ec7943ee.png)

2022-03-13 14:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/TokenController.cs
> +        var userName = User.Claims
Дело вкуса, но я бы переписал так

```suggestion
        var userName = User.Claims
        .Where(x => x.Type == ClaimTypes.Name)
        .Select(x => x.Value)
        .FirstOrDefault();
```

либо

```suggestion
        var user = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Name);
        var userName = user?.Value;
```

2022-03-13 14:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/TokenController.cs
> +        try
Че-т вообще не нравится такой большой try. Если хочешь, можешь как-нибудь сузить область отлова ошибки?

2022-03-13 14:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/TokenController.cs
> +            var userName = User.Claims
Встречается дважды. Есть смысл написать екстеншн либо функу.

2022-03-13 14:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +        if (user == null || !await userManager.CheckPasswordAsync(user, loginModel.Password))
Возможно имеет смысл разбить на два if.

2022-03-13 14:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +        var userName = User.Claims
3-й раз вижу этот поиск username.

2022-03-13 14:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +        if (!await roleManager.RoleExistsAsync(UserRoles.User))
await в if смотрится не очень. Можем обсудить, имеет ли смысл так писать.

2022-03-13 14:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +        var userName = User.Claims
Молчу.

2022-03-13 14:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +        if (changePasswordResult.Succeeded)
Маленькая придирка, можешь не править, но кажется, что было бы круче, если бы BadRequest был выше Ok.

2022-03-13 14:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Models/JwtTokenConfig.cs
>      public int AccessTokenExpiration { get; set; }
Вот это немного раздражает

![image](https://user-images.githubusercontent.com/55148949/158063050-7a707e23-b9a9-418a-a974-70cce07e20b8.png)

Можно навесить ignore, либо сделать nullable

2022-03-13 14:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Models/LoginResult.cs
> +public record LoginResult(string AccessToken, DateTime ExpiredAt,
Где-то делаешь параметры столбиком по одному, где-то - как карта ляжет.

2022-03-13 14:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Services/JwtAuthService.cs
> +        var userName = principal.Claims
...

2022-03-13 14:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/appsettings.json
> +  "Email": {
Ну давайте держать все настройки в открытом доступе.

2022-03-13 14:32 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +        var userName = User.Claims
В дальнейшем будет CurrentUserProvider

2022-03-13 14:32 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +        if (!await roleManager.RoleExistsAsync(UserRoles.User))
Ну убери await и сделай .Wait()

2022-03-13 14:33 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +        var userName = User.Claims
Это правильно

2022-03-13 14:34 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/appsettings.json
> +  "Email": {
Таска в project висит

2022-03-13 14:34 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Services/JwtAuthService.cs
> +        var userName = principal.Claims
...

2022-03-13 14:34 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Models/LoginResult.cs
> +public record LoginResult(string AccessToken, DateTime ExpiredAt,
Refactor and Cleanup

2022-03-13 14:35 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +        if (!await roleManager.RoleExistsAsync(UserRoles.User))
Я имел в виду вынести в переменную результать await.

2022-03-13 14:35 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Models/JwtTokenConfig.cs
>      public int AccessTokenExpiration { get; set; }
ok. ignore

2022-03-13 14:35 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +        if (!await roleManager.RoleExistsAsync(UserRoles.User))
зачем?

2022-03-13 14:36 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +        if (!await roleManager.RoleExistsAsync(UserRoles.User))
Ну, как-то странно выглядит, что мы отрицаем await.

2022-03-13 14:37 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +        var userName = User.Claims
А зачем? Можно же просто екстеншн навесить

2022-03-13 14:38 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +        if (user == null || !await userManager.CheckPasswordAsync(user, loginModel.Password))
Нет особой нужды, так как ответ всегда будет одним и тем же, потому что мы не хотим сообщать пользователю, что пароль неверен

2022-03-13 14:39 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +        if (!await roleManager.RoleExistsAsync(UserRoles.User))
```suggestion
        var roleExists = await roleManager.RoleExistsAsync(UserRoles.User);
        if (!roleExists)
```

2022-03-13 14:39 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +        var userName = User.Claims
возможно, это не все что нам нужно будет уметь делать с текущим пользователем

2022-03-13 14:40 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +        if (!await roleManager.RoleExistsAsync(UserRoles.User))
Можно написать == false

2022-03-13 14:41 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +        if (user == null || !await userManager.CheckPasswordAsync(user, loginModel.Password))
Я из соображений красоты когда говорил. Имелось в виду следующее:
```suggestion
        if (user == null)
            return Unauthorized();
        var isCorrectPassword = await userManager.CheckPasswordAsync(user, loginModel.Password);
        if (!isCorrectPassword)
            return Unauthorized();
        
```

2022-03-13 14:42 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +        if (!await roleManager.RoleExistsAsync(UserRoles.User))
if (await B == false) 👎

2022-03-17 19:22 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Infrastructure/EmailConfiguration.cs
> +﻿namespace Eventnet.Infrastructure;
Это конфиг, тут нужны сеттеры, ну окей, задизэйблю варнинг

2022-03-18 09:19 UTC, IvanSibirtsev requested changes

2022-03-18 09:19 UTC, IvanSibirtsev commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +            "jopa",
ok

2022-03-18 14:58 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Models/Authentication/Tokens/JwtTokenConfig.cs
>  ﻿#pragma warning disable CS8618
Забыл удалить старую версию

![image](https://user-images.githubusercontent.com/55148949/159024049-764b3160-bc3d-46d2-b2de-ac914c89f3bf.png)

2022-03-18 14:58 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api.UnitTests/JwtAuthServiceShould.cs
> +public class JwtAuthServiceShould
Не знаю, мб это у меня бредовая идея, но я предлагаю использовать Should-naming класса для интеграционных тестов и обычный Tests-naming для unit. 

Объясняю почему: в интеграционных тестах мы обычно тестим один метод в классе (ну, я так предполагаю). Просто потому что это удобнее, но в unit-тестах мы можем тестировать несколько методов. 

Можем обсудить.

2022-03-18 14:58 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api.UnitTests/JwtAuthServiceShould.cs
> +    public void Generate_Access_Token_With_Config_Data()
Не соответствует неймингу методов у меня. Нужно договориться о нейминге.

2022-03-18 14:58 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Services/CurrentUserService.cs
> +    public CurrentUserService(IHttpContextAccessor httpContextAccessor,
Имеет ли смысл вместо передачи contextAccessor-a в параметр передавать контекст в параметр? Или он недоступен из контроллера?

2022-03-18 15:16 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Services/CurrentUserService.cs
> +    public CurrentUserService(IHttpContextAccessor httpContextAccessor,
Доступен, считаю, что лучше инкапсулировать это дело

2022-03-18 15:16 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api.UnitTests/JwtAuthServiceShould.cs
> +public class JwtAuthServiceShould
Давай завтра с утра похоливарим на эту тему. Готовь аргументы.

2022-03-18 15:16 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Services/CurrentUserService.cs
> +    public CurrentUserService(IHttpContextAccessor httpContextAccessor,
В плане инкапсулировать? Ты же даже если будешь передавать его через параметр инкапсулируешь в основном классе.

2022-03-18 15:19 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Services/CurrentUserService.cs
> +    public CurrentUserService(IHttpContextAccessor httpContextAccessor,
Зачем мне передавать это в метод каждый раз, если можно скрыть это за сервисом? Да и кажется тому, коо будет пользоваться данным методом без этого параметра будет куда удобней

2022-03-18 15:21 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Services/CurrentUserService.cs
> +    public CurrentUserService(IHttpContextAccessor httpContextAccessor,
Честно говоря, ContextAccessor выглядит как какой-то костыль. Непонятно, как он выбирает нужный контекст. Мб по потоку? Было бы гораздо понятнее, если бы контроллер сам сообщал контекст. Но можешь сделать на свое усмотрение.

2022-03-18 17:58 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Services/CurrentUserService.cs
> +    public CurrentUserService(IHttpContextAccessor httpContextAccessor,
Могу сделать как extensions для HttpContext, будет норм?

2022-03-18 17:59 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Models/Authentication/Tokens/JwtTokenConfig.cs
>  ﻿#pragma warning disable CS8618
Не понял

2022-03-18 19:04 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Services/CurrentUserService.cs
> +    public CurrentUserService(IHttpContextAccessor httpContextAccessor,
Не вижу смысла делать это экстеншеном для HttpContext. Кажется, слишком специфичный метод.

2022-03-18 19:06 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Services/CurrentUserService.cs
> +    public CurrentUserService(IHttpContextAccessor httpContextAccessor,
Ну так в этом и тролинг, чтобы инкапсулировать все это в один сервис, чтобы никому не пришлось думать ни про какие HttpContext. Просто GetCurrentUser и все

2022-03-18 19:07 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Services/CurrentUserService.cs
> +    public CurrentUserService(IHttpContextAccessor httpContextAccessor,
Лично я когда смотрю на использование этого метода не понимаю, как из контроллера он понимает, какой юзер обращается, в отличие от случая, если бы был проброшен контекст.

2022-03-18 19:08 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Services/CurrentUserService.cs
> +    public CurrentUserService(IHttpContextAccessor httpContextAccessor,
Хочешь сделаю в сервисе отдельный метод в который надо будет прокидывать контекст?

2022-03-18 19:10 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Services/CurrentUserService.cs
> +    public CurrentUserService(IHttpContextAccessor httpContextAccessor,
Что толку, если ты будешь продолжать использовать метод без параметра? Даже я бы использовал. Будь как ток, он умный.
Короче, решай сам, я высказал аргумент против такой сигнатуры. Если он неубедителен, оставляй.

2022-03-18 19:10 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Services/CurrentUserService.cs
> +    public CurrentUserService(IHttpContextAccessor httpContextAccessor,
Аргумент принят к сведенью, оставлю так.

2022-03-23 16:16 UTC, IvanSibirtsev approved these changes

2022-03-23 16:20 UTC, gODeaLoAple approved these changes

2022-03-23 16:21 UTC, merged