Event filter service basic implementation
HardSign-Team/eventnet-backend pull request #4
Opened 2022-03-14 14:40 UTC by gODeaLoAple

2022-03-14 17:18 UTC, DaGnYMilleR requested changes
Почему логика в API? фильтры это вроде как часть domain...

2022-03-14 17:18 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +    private void ValidateFilterModel(FilterEventsModel filterModel)
Можно навесить аттрибут на модель и не делать этой проверки (да, тогда придется создать отдельную модель инпута и маппить ее, но это логично)

2022-03-15 17:56 UTC, lapakota commented on Eventnet/Eventnet.Api.IntegrationTests/EventControllerTests/GetEventsShould.cs
> +#pragma warning disable CS8625
Кс Го

2022-03-15 17:56 UTC, lapakota approved these changes

2022-03-17 19:49 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
>      public const int MaxPageSize = 20;
Точно ли эти константы должны быть здесь?

2022-03-17 19:58 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +            .Select(dbContext.Events.AsEnumerable(), maxCount)
Имхо, но смотрится странновато
selector.Select
мб SelectFrom?

2022-03-17 19:58 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +        if (filterModel is null) return BadRequest("Cannot parse filter model");
Почему где-то после условия нет переноса строки, а где-то есть?

2022-03-17 19:58 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Domain/Events/Filters/EventFilters/BaseDateFilter.cs
> +            DateEquality.SameDay => date.Date == borderDate.Date,
SameDay, а сравниваешь целиком DateTime.
Может использовать DateOnly struct?
Хотя у события может быть и вполне определенное время

2022-03-17 19:58 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Domain/Events/Filters/EventFilters/BaseDateFilter.cs
> +            _                    => throw new ArgumentOutOfRangeException()
Прокинуть бы текст какой-нить

2022-03-17 20:00 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Domain/Events/Filters/Data/DateEquality.cs
> +﻿namespace Eventnet.Domain.Events.Filters.Data;
Что такое Data?

2022-03-17 20:09 UTC, DaGnYMilleR requested changes
Фильтры реализованы круто

2022-03-17 20:09 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/UserController.cs
> +    [HttpGet("searchByPrefix/{prefix:alpha:required}")]
Вроде в роутинге обычно используется kebab-case

2022-03-17 20:09 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +    [HttpGet("searchByName/{eventName}")]
Вроде в роутинге обычно используется kebab-case

2022-03-17 20:09 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +        if (eventEntity is null) return NotFound();
Коммент относится к [HttpPost("create")]
Вроде ж из Post итак понятно, что будет create

2022-03-18 02:23 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +            .Select(dbContext.Events.AsEnumerable(), maxCount)
Мне не кажется это странным.

2022-03-18 02:24 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +        if (filterModel is null) return BadRequest("Cannot parse filter model");
Потому что плохо настроил форматирование. Буду признателен, если скажешь, где находится условие, чтобы всегда переводить на новую строку в таком случае.

2022-03-18 02:25 UTC, gODeaLoAple commented on Eventnet/Eventnet.Domain/Events/Filters/EventFilters/BaseDateFilter.cs
> +            DateEquality.SameDay => date.Date == borderDate.Date,
Наверное, нейминг не тот. Имелась в виду та же дата, но без учета времени.

2022-03-18 02:26 UTC, gODeaLoAple commented on Eventnet/Eventnet.Domain/Events/Filters/Data/DateEquality.cs
> +﻿namespace Eventnet.Domain.Events.Filters.Data;
Дата.
Всякие данные навроде этого enum.

2022-03-18 02:27 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +        if (eventEntity is null) return NotFound();
1. POST - это же не всегда создание? Или типа раз нет action, то по-умолчанию создание?
2. Я делегировал этот метод Ивану.

2022-03-18 02:48 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +            .Select(dbContext.Events.AsEnumerable(), maxCount)
Ок

2022-03-18 02:49 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +        if (filterModel is null) return BadRequest("Cannot parse filter model");
Я не знаю

2022-03-18 02:49 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Domain/Events/Filters/EventFilters/BaseDateFilter.cs
> +            DateEquality.SameDay => date.Date == borderDate.Date,
Ну так а в коде же учитывается время...

2022-03-18 02:50 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Domain/Events/Filters/Data/DateEquality.cs
> +﻿namespace Eventnet.Domain.Events.Filters.Data;
Непривычно) 
Окей

2022-03-18 02:53 UTC, gODeaLoAple commented on Eventnet/Eventnet.Domain/Events/Filters/EventFilters/BaseDateFilter.cs
> +            DateEquality.SameDay => date.Date == borderDate.Date,
Property Date возвращает дату без времени.

2022-03-18 02:53 UTC, gODeaLoAple commented on Eventnet/Eventnet.Domain/Events/Filters/EventFilters/BaseDateFilter.cs
> +            DateEquality.SameDay => date.Date == borderDate.Date,
https://docs.microsoft.com/ru-ru/dotnet/api/system.datetime.date?view=net-6.0

2022-03-18 02:54 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
>      public const int MaxPageSize = 20;
Можно было бы и в конфиг вынести, не не уверен, что это резонно.

2022-03-18 02:55 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +        if (eventEntity is null) return NotFound();
Ну так у нас же путь api/events/
И по rest create писать не нужно

2022-03-18 03:08 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
>      public const int MaxPageSize = 20;
Ну мб в какой-нить связанный с этим класс
Но наверн похер

2022-03-18 03:08 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Domain/Events/Filters/EventFilters/BaseDateFilter.cs
> +            DateEquality.SameDay => date.Date == borderDate.Date,
Круто

2022-03-18 03:09 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
>      public const int MaxPageSize = 20;
Похер +

2022-03-18 09:12 UTC, IvanSibirtsev approved these changes

2022-03-18 13:55 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +        if (filterModel is null) return BadRequest("Cannot parse filter model");
![image](https://user-images.githubusercontent.com/55148949/159015944-ea8dc59c-fdc7-4204-82d5-45900f02f44a.png)

2022-03-18 15:19 UTC, DaGnYMilleR approved these changes

2022-03-18 15:21 UTC, merged