Create event
HardSign-Team/eventnet-backend pull request #5
Opened 2022-03-18 16:17 UTC by IvanSibirtsev

2022-03-18 19:04 UTC, DaGnYMilleR requested changes
пока subject не jopa - не приму

2022-03-18 19:04 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +    private readonly UserManager<UserEntity> userManager;
Field 'userManager' is assigned but its value is never used

2022-03-18 19:04 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +        if (createModel is null)
Expression is always false

2022-03-18 19:04 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +        eventSaveService.Save(createdEvent, files);
Метод же асинхронный. Обычно для них используют постфикс Async
Ну и await, да

2022-03-18 19:04 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +    [HttpGet("isCreated")]
kebab

2022-03-18 19:04 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +            StatusCode = StatusCodes.Status202Accepted
можно заменить на return Accepted();

2022-03-18 19:04 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +    public IActionResult GenerateEventGuid()
вкусовщина, но я бы предпочел inline, хотя, зная наших любителей писать скобки вместо лямбд...

2022-03-18 19:04 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Config/ApplicationMappingProfile.cs
> +        CreateMap<Event, CreateEventModel>()
Ниче не понял, что ты тут хотел сделать. Но почему мы ставим юзеру новый id?

2022-03-18 19:04 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Eventnet.Api.csproj
> +        <PackageReference Include="PagedList.Mvc" Version="4.5.0" />
![image](https://user-images.githubusercontent.com/37438377/159059885-0eb5eb67-9144-4677-b507-22e688895ec9.png)
чета с либами не то...

2022-03-18 19:04 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Services/IPhotosToTempSaveService.cs
> +public interface IPhotosToTempSaveService
to temp что? кажется не хватает folder

2022-03-18 19:04 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Services/IEventSaveService.cs
> +public interface IEventSaveService
Общий коммент. Стоит поместить эти сервисы в отдельную подпапку, шоб у нас каша не получалась

2022-03-18 19:04 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +    [HttpPost]
надо бы [Authorize] навесить

2022-03-18 19:04 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +        var createdEvent = mapper.Map<Event>(createModel);
А откуда тут ваще id для евента возьмется? Возможно тогда это просто опечатка в маппере и там должно быть не UserId?

2022-03-18 19:04 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Models/CreateEventModel.cs
> +    Location Location,
Не могу оставить коммент выше. Пользователь может создавать событие только для себя самого? Если да то стоит id пользователя получать через CurrentUserService(дописать там метод для его получения) который у меня лежит в еще на данный момент не вмерженном пре

2022-03-18 19:04 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Services/EventSaveService.cs
> +        var path = photosToTempSaveService.SaveToTemp(savedEvent.Id, photos);
кажется, что мы можем хотеть от фотки не просто ее наличие, но и какуюнить доп инфу(например, размер, расширение etc). Давайте обсудим.

2022-03-18 19:04 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Services/Handler.cs
> +public class Handler
кажется, что имя handler не совсем полностью отражает суть...

2022-03-18 19:04 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Services/Handler.cs
> +        return value;
Possible null reference return.

2022-03-18 19:04 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Services/Handler.cs
> +    public void Update(Guid id, SaveEventResult value)
ну этот метод же не только Update но и Add делает...

2022-03-18 19:04 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Services/Handler.cs
> +        // может ли возникнуть ситуация когда нужно будет использовать TryUpdate ?
кажется, что лучше не *** мозга, а заюзать AddOrUpdate

2022-03-18 19:04 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Services/PublishEventService.cs
> +        var connection = factory.CreateConnection();
connection и channel IDisposable

2022-03-18 19:04 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Infrastructure/SaveToDbService.cs
> +        dbContext = factory.CreateScope().ServiceProvider.GetRequiredService<ApplicationDbContext>();
А в чем проблема сразу ApplicationDbContext прокинуть?

2022-03-18 19:04 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Infrastructure/ImageServices/ILoadFromTempService.cs
> +public interface ILoadFromTempService
А почему SaveToTemp в одном проекте, а Load в другом?

2022-03-18 19:04 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Infrastructure/ImageServices/LoadFromTempService.cs
> +            File.Delete(filename); // возможно, их стоит удалять в другой момент
Кажется. что да. Потому что при загрузке фоток совсем не ожидаешь, что они пропадут)

2022-03-18 19:04 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Services/ConsumeEventService.cs
> +            rabbitMqMessageHandler.Handle(message);
Possible null reference argument for parameter 'rabbitMqMessage' in 'Eventnet.Services.IRabbitMqMessageHandler.Handle'.

2022-03-18 19:04 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Services/Handler.cs
> +    public bool ContainsInformationAbout(Guid id) => saveEventInformation.ContainsKey(id);
Кажется, что тут может что-то пойти не так, так как ты сначала проверяешь, что ключ есть, а затем берешь значение. Между этими двумя действиями может вклиниться какой-нить другой поток, которому Handler тоже ответит true, и удалить раньше. TryGetValue тут подойдет наверн

2022-03-18 19:04 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Services/PhotosToTempSaveService.cs
> +            var filePath = Path.Combine(eventPhotosPath, file.FileName);
Что будет, если файл с таким именем уже есть в temp? Если требуется сохранить имя исходного файла, то где-то выше я уже писал, о том что нужна отдельная модель для фоток, так вот, это можно туда же

2022-03-18 19:04 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Services/PhotosToTempSaveService.cs
> +        var eventPhotosPath = Path.Combine(pathToPhotos, id.ToString());
Постой брат. Мы создаем для каждого заявления отдельную папку? С тем учетом, что у нас в среднем для каждого события будет 1 фотка(личные ощущения)? Так как ты возвращаешь путь до файла, то можно его генерить через Guid или Path.GetRandomFileName(). Надо обсудить.

2022-03-18 19:04 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Services/RabbitMqMessageHandler.cs
> +            if (validator.Validate(photos, out exception))
А разве нам не нужно валидировать данные самого события? Имя там, даты и т.п.

2022-03-18 19:04 UTC, DaGnYMilleR commented on Eventnet/Eventnet.DataAccess/PhotosEntity.cs
> +    public string pathToPhotos { get; set; }
Свойство с маленькой строки? -_-

2022-03-18 19:04 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Services/RabbitMqConfig.cs
> +public class RabbitMqConfig
Стоит читать хотяб из appsettings.json наверн, пока мы не прикрутили нормальные переменные среды

2022-03-18 19:04 UTC, DaGnYMilleR commented on Eventnet/Eventnet.DataAccess/ApplicationDbContext.cs
> +    public DbSet<PhotosEntity> Photos { get; set; }
А чо где миграция?

2022-03-18 19:04 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Domain/Eventnet.Domain.csproj
> +        <ProjectReference Include="..\Eventnet.DataAccess\Eventnet.DataAccess.csproj" />
Domain зависит от DataAccess? Точно нет, проходили в PathFindere такое....

2022-03-18 19:04 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Infrastructure/ImageServices/IImageToDbPreparer.cs
> +public interface IImageToDbPreparer
Preparer и метод Save. Го обсудим

2022-03-20 13:30 UTC, gODeaLoAple requested changes
Нет тестов - нет аппрува. Без негатива.

2022-03-20 13:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +    public IActionResult GenerateEventGuid()
В контроллерах только statement-body!

2022-03-20 13:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Services/EventSaveService.cs
> +    public async void Save(Event savedEvent, IFormFile[] photos)
```suggestion
    public async void Save(Event eventForSave, IFormFile[] photos)
```

2022-03-20 13:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Services/Handler.cs
> +    public void Update(Guid id, SaveEventResult value)
В EFCore такой же нейминг. Считаю, что можно просто Update оставить.

2022-03-20 13:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Services/Handler.cs
> +﻿using System.Collections.Concurrent;
Кажется, что имеет смысл вынести либо в домейн, либо в инфру, т.к. по факту это просто кеш.

2022-03-20 13:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Services/RabbitMqMessageHandler.cs
> +            if (validator.Validate(photos, out exception))
Почему Validate имеет такой интерфейс? Может, стоит кидать ошибку, если данные неконсистенты? 
Для этого можно просто создать какой-нибудь EventCreationValidationException и либо наследоваться от него, либо просто в него сообщение пробрасывать. out параметр выглядит лишним.

2022-03-20 13:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Services/RabbitMqMessageHandler.cs
> +                saveToDbService.SaveImages(photos, id);
Даже тут надо сначала сохранить ивент, а потом изображения, потому что на у фоток будет foreign key на ивент.

2022-03-20 13:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Services/RabbitMqMessageHandler.cs
> +                saveToDbService.SaveEvent(rabbitMqMessage);
Почему saveToDbService принимает rabbitMqMessage?

2022-03-20 13:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.DataAccess/PhotosEntity.cs
> +﻿namespace Eventnet.DataAccess;
Доработать модель. Сделать более консистентной. 
1. ForeignKey -> Event
2. Create configuration

2022-03-20 13:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Infrastructure/ISaveToDbService.cs
> +    void SaveEvent(RabbitMqMessage message);
SaveEvent, но принимает RabbitMqMessage

2022-03-20 13:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Infrastructure/ISaveToDbService.cs
> +    void SaveImages(List<Image> images, Guid id);
Непонятно, к чему относится id. Возможно исчезнет после переосмысления модели Image в бд.

2022-03-20 13:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Infrastructure/ImageServices/IImageToDbPreparer.cs
> +public interface IImageToDbPreparer
Плохой нейминг.

2022-03-20 13:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Infrastructure/ImageServices/IImageToDbPreparer.cs
> +    string Save(List<Image> images, Guid id);
Странный интерфейс и название.

2022-03-20 13:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Infrastructure/ImageServices/ImageToDbPreparer.cs
> +            image.Save(path, ImageFormat.Jpeg);
Нет обработки ошибок. Возможно, в случае ошибок надо возвращать файлы, которыене удалось сохранить.

2022-03-20 13:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Infrastructure/ImageServices/LoadFromTempService.cs
> +            File.Delete(filename); // возможно, их стоит удалять в другой момент
Согласен, удалять надо только в случае успешного перемещения.

2022-03-20 13:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Infrastructure/SaveToDbService.cs
> +        dbContext.Events.Add(eventEntity);
Ты уверен, что сохраняешь event?

2022-03-20 13:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Infrastructure/SaveToDbService.cs
> +        dbContext.Photos.Add(photosEntity);
Ты уверен, что сохраняешь photo?

2022-03-20 13:40 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Services/RabbitMqMessageHandler.cs
> +            if (validator.Validate(photos, out exception))
Как альтернативу бросинию ошибки предложу возвращать какой нить ValidationResult

2022-03-20 13:42 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Services/RabbitMqMessageHandler.cs
> +            if (validator.Validate(photos, out exception))
Че мелочиться, подрубай монады!

2022-04-05 18:13 UTC, DaGnYMilleR requested changes

2022-04-05 18:13 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +    private readonly IEventSaveService eventSaveService;
![image](https://user-images.githubusercontent.com/37438377/161816134-5fd8b8d8-dd1e-4bb1-80f2-6266b830a641.png)

2022-04-05 18:13 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +    private readonly UserManager<UserEntity> userManager;
епта

2022-04-05 18:13 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +    [HttpGet("guid")]
Зачем этот эндпоинт нужен?(я задавал этот вопрос, ответа не было, теперь придется)
Почему бы из create-event id не возвращать?

2022-04-05 18:13 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +            return BadRequest(exception);
А почему кидаем BadRequest? У нас же может быть такое, что событие еще не создано, а это вроде как не исключительная ситуация

2022-04-05 18:13 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Models/CreateEventModel.cs
> +    DateTime? EndDate,
А почему у события может не быть конца?

2022-04-05 18:13 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Infrastructure/Handler.cs
> +public class Handler
Чому handler то?

2022-04-05 18:13 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Services/SaveServices/RabbitMqConfig.cs
> +public class RabbitMqConfig
Ну это же конфиг, почему он в сервисах?
Да и лучше читать это дело из appsettings.json

2022-04-05 18:13 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Services/SaveServices/EventSaveService.cs
> +    private async Task<List<byte[]>> GetStreamsAsync(IFormFile[] photos)
static?

2022-04-05 18:13 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Eventnet.Api.csproj
> +        <PackageReference Include="PagedList.Mvc" Version="4.5.0" />
________(или это в другой ветке зафикшено?)

2022-04-05 18:13 UTC, DaGnYMilleR commented on Eventnet/Eventnet.DataAccess/ApplicationDbContext.cs
> +    public DbSet<PhotoEntity> Photos { get; set; }
Так тыж не зааплаил конфигурацию...
builder.ApplyConfiguration(new EventConfiguration());

2022-04-05 18:13 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Domain/Eventnet.Domain.csproj
>      </PropertyGroup>
коммент к файлам Event и Location, там неймспейс говна

2022-04-05 18:13 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Infrastructure/PhotoServices/PhotoToStorageSaveService.cs
> +    private const string DirToSave = "storage";
Путь до файла с фотками лучше из конфига читать

2022-04-05 18:13 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Infrastructure/Validators/EventCreationValidator.cs
> +    private string FormatException(string photoException, string eventException) => (photoException + " " + eventException).Trim();
static

2022-04-05 18:13 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Infrastructure/Validators/EventCreationValidationResult.cs
> +public record EventCreationValidationResult(string Exception, bool IsOk);
IsOk лучше сделать первым параметром и в Exception(лучше назвать типа ErrorMessage btw) сделать по умолчанию = string.Empty

2022-04-05 18:13 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Infrastructure/Validators/PhotoValidator.cs
> +        // надо придумать что проверять на бэкенде.
Ну, размер хотим проверять, что б нам earth.bmp не закинули

2022-04-06 06:15 UTC, IvanSibirtsev commented on Eventnet/Eventnet.Api/Models/CreateEventModel.cs
> +    DateTime? EndDate,
тут такое устроили. Итог: я не знаю, давай оставим это и не будем к этому возвращаться

2022-04-06 06:22 UTC, IvanSibirtsev commented on Eventnet/Eventnet.Api/Models/CreateEventModel.cs
> +    DateTime? EndDate,
Ребята не стоит вскрывать эту тему. Вы молодые, шутливые, вам все легко. Это не то. Это не Чикатило и даже не архивы спецслужб. Сюда лучше не лезть. Серьезно, любой из вас будет жалеть. Лучше закройте тему и забудьте что тут писалось. Я вполне понимаю что данным сообщением вызову дополнительный интерес, но хочу сразу предостеречь пытливых - стоп. Остальных просто не найдут.

2022-04-07 18:30 UTC, gODeaLoAple requested changes
На самом деле большинство сервисов могут быть зарегистрированы Scoped, тогда не будет проблем с инджектом DbContext. Синглтон нужен в основном для хандлеров.

Ну и да. Нет тестов - нет аппрува.

2022-04-07 18:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Services/SaveServices/ConsumeEventService.cs
>          consumer.Received += (ch, ea) =>
```suggestion
        consumer.Received += (_, ea) =>
```
  <Eventnet.Api>\Services\SaveServices\ConsumeEventService.cs:813 Parameter 'ch' is never used

2022-04-07 18:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +        await eventSaveService.SaveAsync(createdEvent, photos);
Заренеймить нормально.

2022-04-07 18:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
>      // TODO use format https://datatracker.ietf.org/doc/html/rfc6902
А почему нет редактирования? Ну, то есть update-a события

2022-04-07 18:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
>      [HttpGet("guid")]
```suggestion
    [HttpGet("request-event-creation")]
```
Может быть так?

2022-04-07 18:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +            return BadRequest("Too large images. Recommended size of all images is 128Mb.");
Почему размер захардкожен?

2022-04-07 18:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Services/SaveServices/IPublishEventService.cs
> +    Task SendAsync(string message);
Ну раз это IPublishService, то пусть функция и называется соответствующе?
```suggestion
    Task PublishAsync(string message);
```

2022-04-07 18:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.DataAccess/PhotoEntity.cs
> +    public Guid Id { get; set; }
```suggestion
    public Guid Id { get; private set; }
```

2022-04-07 18:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.DataAccess/PhotoEntity.cs
> +    public Guid EventId { get; set; }
```suggestion
    public Guid EventId { get; }
```

2022-04-07 18:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Infrastructure/PhotoServices/PhotoToStorageSaveService.cs
> +        var path = Path.Combine(dirToSave, photoId + ".jpeg");
Почему jpeg? Почему захардкожено?

2022-04-07 18:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Infrastructure/RabbitMqMessageHandler.cs
> +            Console.WriteLine(e);
Надо больше console.log

2022-04-07 18:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Infrastructure/SaveToDbService.cs
> +        await using var dbContext = factory.CreateScope().ServiceProvider.GetRequiredService<ApplicationDbContext>();
А почему ты не хочешь контекст прокидывать в конструктор? Можно же сервис тоже сделать скопед. Либо раз уж на то пошло, лучше инджектить ContextFactory, а не IServiceScopeFactory.

2022-04-07 18:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Infrastructure/Validators/EventCreationValidationResult.cs
> +public record EventCreationValidationResult(bool IsOk, string ErrorMessage);
Мне кажется, пора уже добавить Either куда-нибудь в инфраструктуру и использовать его.

2022-04-07 18:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +        return Accepted();
А ведь если пользователь не прикрепил ни одной фотографии, то событие может быть сохранено быстро, и ответ можно отправить сразу же. Просто вкинул идею на подумать.

2022-04-07 18:39 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
>      [HttpGet("guid")]
Только давайте не будем здесь id возвращать, пожалуйста, мне прост кажется, что получать id где-то отдельно от создания события не очень хорошо....

2022-04-12 06:48 UTC, gODeaLoAple requested changes
Доработать некоторые моменты, в остальном все нормально

2022-04-12 06:48 UTC, gODeaLoAple commented on Eventnet/Eventnet.Infrastructure/RabbitMqMessageHandler.cs
> +            status = result.IsOk ? EventSaveStatus.Saved : EventSaveStatus.NotSavedDueToUserError;
Вкусовщина, но...
```suggestion
            if (result.IsOk)
            {
                saveToDbService.SaveEvent(eventForSave);
                saveToDbService.SavePhotos(photos, id);
                status = EventSaveStatus.Saved;
            }
            else
            {
                status = EventSaveStatus.NotSavedDueToUserError;
            }
```

2022-04-12 06:48 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api.IntegrationTests/EventControllerTests/CreateEventTests/CreateEventShould.cs
> +    }
Некритично, но я бы все вспомогательные методы перемещал вниз.

2022-04-12 06:48 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api.IntegrationTests/EventControllerTests/CreateEventTests/CreateEventShould.cs
> +public class CreateEventTestsShould : CreateEventTestsBase
Не хватило теста на повторное сохранение того же события. По идее, должно отклонить, либо полностью заменить, но не сохранить оба.

2022-04-12 06:48 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api.IntegrationTests/EventControllerTests/CreateEventTests/CreateEventShould.cs
> +public class CreateEventTestsShould : CreateEventTestsBase
И хочется убедиться, что фотография сохранится.

2022-04-12 06:48 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api.IntegrationTests/EventControllerTests/CreateEventTests/CreateEventShould.cs
> +public class CreateEventTestsShould : CreateEventTestsBase
Желательно проверить, что путь из бд будет указывать на реально существующий файл.

2022-04-12 06:48 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
>          await eventSaveService.SaveAsync(createdEvent, photos);
Забыл переименовать

2022-04-12 06:48 UTC, gODeaLoAple commented on Eventnet/Eventnet.DataAccess/Configurations/PhotoConfiguration.cs
> +            // builder.Property(x => x.EventId);
А вот это надо бы удалить, а не закомментить

2022-04-12 06:48 UTC, gODeaLoAple commented on Eventnet/Eventnet.Domain/Photo.cs
> +            _            => throw new ArgumentOutOfRangeException($"Unknown content type {contentType}")
Возможно, имело бы смысл добавить кастомную ошибку формата изображения. UnsupportedImageFileException, например

2022-04-12 06:48 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Services/SaveServices/EventSaveService.cs
> +            Console.WriteLine(e);
Такое неодобряем. Надо Васю запрячь добавить логирование

2022-04-12 06:48 UTC, gODeaLoAple commented on Eventnet/Eventnet.DataAccess/Configurations/PhotoConfiguration.cs
> +            // builder.Property(x => x.EventId);
Удалить, а не закомментить.

2022-04-12 06:48 UTC, gODeaLoAple commented on Eventnet/Eventnet.DataAccess/Migrations/ApplicationDbContextModelSnapshot.cs
> +                        .HasColumnType("timestamp without time zone");
Интересно, как это получилось. наверное, нам нужны таймзоны

2022-04-12 06:48 UTC, gODeaLoAple commented on Eventnet/Eventnet.Domain/Photo.cs
> +            _            => throw new ArgumentOutOfRangeException($"Unknown content type {contentType}")
Возможно, стоит использовать кастомный exception. UnsupportedImageFormat.

2022-04-12 06:48 UTC, gODeaLoAple commented on Eventnet/Eventnet.Infrastructure/Validators/EventCreationValidator.cs
> +        (photoErrorMessage + " " + eventErrorMessage).Trim();
Ну это кал, конечно, но пока плевать.

2022-04-16 04:05 UTC, gODeaLoAple approved these changes
В принципе, можно мержить, но лучше бы немного причесать.

2022-04-16 04:05 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api.IntegrationTests/EventControllerTests/CreateEventTests/CreateEventShould.cs
>          response.StatusCode.Should().Be(HttpStatusCode.BadRequest);
Коммент к названию класса. В интеграционных тестах нейминг такой: {MethodName}Should
И каждый метод - Response{Code}[_When{Condition}[_And{Condition}]...]. 
короче, просто убери "Tests" из названия :)

2022-04-16 04:05 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api.IntegrationTests/EventControllerTests/CreateEventTests/CreateEventShould.cs
> +    private async Task<HttpResponseMessage> PostAsync(Guid eventId, Guid ownerId, FileStream fileStream, string mediaType)
[Optional] Было бы неплохо заренеймить во что-то, что более четко отражало суть метода. Типа RequestSave или в таком духе.

2022-04-16 04:05 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Services/SaveServices/EventSaveService.cs
> +            Console.WriteLine(e);
x2

2022-04-16 04:05 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Services/SaveServices/EventSaveService.cs
> +
Плохой нейминг. В одних методах уточняешь, что сущность относится к Event (GetSaveEventResult), в других - считаешь так по-умолчанию (SaveAsync, ContainsGuid).

```suggestion
    public bool IsSaving(Guid eventId) => handler.ContainsGuid(id);

```

2022-04-16 04:05 UTC, gODeaLoAple commented on Eventnet/Eventnet.Infrastructure/Handler.cs
> +    public bool ContainsGuid(Guid id) => cache.TryGetValue(id, out _);
См. коммент к EventSaveService

2022-04-17 04:37 UTC, gODeaLoAple approved these changes

2022-04-17 04:37 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +        if (WhetherSaveEventBeingHandling(createModel.Id) || isSaved)
Почему Whether, а не Is...

2022-04-17 09:23 UTC, DaGnYMilleR requested changes

2022-04-17 09:23 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +        {
зачем скобки?

2022-04-17 09:23 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +            var recommendedSizeInMb = rabbitMqConfig.RecommendedMessageSizeInBytes / 1024 / 1024;
зачем это считать при каждом вызове метода?

2022-04-17 09:23 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +        var supportedContentTypes = new [] { "image/bmp", "image/png", "image/jpeg" };
тоже стоит делать где-нить выше (хотяб в конструкторе, но лучше еще выше)

2022-04-17 09:23 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +        var contentTypes = files.Select(photo => photo.ContentType);
можно одним All обойтись бтв (но, кажется, что ненужно, так чиатемей)

2022-04-17 09:23 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/EventController.cs
> +        return Ok(id);
Нет, это штука не должна возвращать id, он генериться именно при запросе создания. Тут должны быть проверки на то, может ли юзер создать евент (понятно, что пока этого нет, поэтому можно просто Ok() возвращать)

2022-04-17 09:23 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Services/SaveServices/EventSaveService.cs
> +            return new SaveEventResult(EventSaveStatus.NotSavedDueToUserError, "No such Guid");
зачем говорить, о том что у нас Guid, фронтендеры вообще не знают, что это такое, у них UUID вроде

2022-04-17 09:23 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Services/SaveServices/EventSaveService.cs
> +    private readonly Handler handler;
да почему Handler, уже какое ревью пишу об этом ептыть

2022-04-17 09:23 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Services/SaveServices/RabbitMqConfig.cs
> +    public string Queue { get; set; }
![image](https://user-images.githubusercontent.com/37438377/163708404-682d5691-cbdd-47b5-aaac-dbf96e32604d.png)

2022-04-17 09:23 UTC, DaGnYMilleR commented on Eventnet/Domain/Domain.csproj
> +<Project Sdk="Microsoft.NET.Sdk">
в Domain неймспейсы говна
![image](https://user-images.githubusercontent.com/37438377/163708431-fc1549b4-bcef-4857-abfc-fee4b1509e7b.png)

2022-04-17 09:23 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Infrastructure/RabbitMqMessageHandler.cs
> +    private List<Photo> GetPhotos(List<RabbitMqPhoto> rabbitMqPhotos) =>
![image](https://user-images.githubusercontent.com/37438377/163708491-bf719398-e68f-434e-82ee-3d29efade173.png)

2022-04-17 09:56 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Services/SaveServices/RabbitMqConfig.cs
> +    public string Queue { get; set; }
Это же конфиг...

2022-04-17 09:56 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Services/SaveServices/RabbitMqConfig.cs
> +    public string Queue { get; set; }
Хотя Suppress не помешал бы, да.

2022-04-17 19:38 UTC, DaGnYMilleR approved these changes

2022-04-17 19:39 UTC, merged