Restore password
HardSign-Team/eventnet-backend pull request #8
Opened 2022-04-03 07:09 UTC by DaGnYMilleR

2022-04-03 07:49 UTC, gODeaLoAple requested changes

2022-04-03 07:49 UTC, gODeaLoAple commented on Eventnet/Eventnet.DataAccess/Configurations/UserRolesConfiguration.cs
> +                { NormalizedName = UserRoles.User.ToUpper(), ConcurrencyStamp = Guid.NewGuid().ToString() });
Кажется, что так красивее.
```suggestion
            new IdentityRole(UserRoles.Admin)
            {
                NormalizedName = UserRoles.Admin.ToUpper(), 
                ConcurrencyStamp = Guid.NewGuid().ToString()
            },
            new IdentityRole(UserRoles.User)
            { 
                NormalizedName = UserRoles.User.ToUpper(),
                ConcurrencyStamp = Guid.NewGuid().ToString() 
            }
```

2022-04-03 07:49 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +        if (user is null || !await userManager.CheckPasswordAsync(user, loginModel.Password))
Коммент к строке выше (55-56).
А можно ли за один запрос найти по имени или email?

2022-04-03 07:49 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +        if (user is null || !await userManager.CheckPasswordAsync(user, loginModel.Password))
А по телефону будет авторизация?

2022-04-03 07:49 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +    [HttpPost("logout")]
Почему где-то есть xml-документация, а где-то - нет? И вообще за чем она нужна?

2022-04-03 07:49 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +        if (userNameExists is not null)
А че не прямо в if-е?)))

2022-04-03 07:49 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +        return BadRequest(result.ToString());
Я бы инвертировал условие выше, чтобы Ok было последним выражением.

2022-04-03 07:49 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
>      public async Task<IActionResult> SendEmailConfirmation(string userName)
А как userName будет заполнено? Тут автоматически [FromBody] подставляется?

2022-04-03 07:49 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +        if (user is null || !await userManager.IsEmailConfirmedAsync(user))
Опа, а тут await в if... Хм, странно, странно.

2022-04-03 07:49 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Eventnet.Api.csproj
> +
Надо пофиксить форматтирование, похоже.

2022-04-03 07:49 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Models/Authentication/RestorePasswordModel.cs
> +    [Compare("NewPassword", ErrorMessage = "Password and Confirmation Password must match.")]
```suggestion
    [Compare(nameof(NewPassword), ErrorMessage = "Password and Confirmation Password must match.")]
```

2022-04-03 07:49 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Models/LocationFilterModel.cs
> +    double Radius);
Почему так?

2022-04-03 07:49 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Program.cs
> +services.AddScoped<IForgotPasswordService, ForgotPasswordService>();
А почему scoped, а не singletone?

2022-04-03 07:52 UTC, DaGnYMilleR commented on Eventnet/Eventnet.DataAccess/Configurations/UserRolesConfiguration.cs
> +                { NormalizedName = UserRoles.User.ToUpper(), ConcurrencyStamp = Guid.NewGuid().ToString() });
Согласен

2022-04-03 07:52 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +        if (user is null || !await userManager.CheckPasswordAsync(user, loginModel.Password))
По телефону - нет, телефон это прошлый век

2022-04-03 07:52 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +        if (user is null || !await userManager.CheckPasswordAsync(user, loginModel.Password))
> Коммент к строке выше (55-56). А можно ли за один запрос найти по имени или email?

Нет

2022-04-03 07:53 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +    [HttpPost("logout")]
Её нет только для одного очевидного метода.
А нужна для того, чтобы фронты могли понимать, чего от них ждут и что делает метод

2022-04-03 07:53 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +        if (userNameExists is not null)
Посчитал, что так более наглядно (только в данном конкретном случае)

2022-04-03 07:54 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +        return BadRequest(result.ToString());
Сыглы

2022-04-03 07:54 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
>      public async Task<IActionResult> SendEmailConfirmation(string userName)
Да, body

2022-04-03 07:54 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +        if (user is null || !await userManager.IsEmailConfirmedAsync(user))
Ну тут совсем другое проверяется

2022-04-03 07:54 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Eventnet.Api.csproj
> +
Кому?

2022-04-03 07:54 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Models/Authentication/RestorePasswordModel.cs
> +    [Compare("NewPassword", ErrorMessage = "Password and Confirmation Password must match.")]
+

2022-04-03 07:55 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Models/LocationFilterModel.cs
> +    double Radius);
cleanup запустил, он сам это сделал

2022-04-03 07:55 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Program.cs
> +services.AddScoped<IForgotPasswordService, ForgotPasswordService>();
А почему синглтон?

2022-04-03 07:59 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Program.cs
> +services.AddScoped<IForgotPasswordService, ForgotPasswordService>();
Потому что у тебя при создании вроде как ничего динамического не происходит. Все сервисы конфигурируются просто файлом. Зачем тратить время гц на это?

2022-04-03 07:59 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Models/LocationFilterModel.cs
> +    double Radius);
Я понимаю. Я про это и спрашиваю: почему так? Надо поменять форматирование.

2022-04-03 08:00 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Models/Authentication/RestorePasswordModel.cs
> +    [Compare("NewPassword", ErrorMessage = "Password and Confirmation Password must match.")]
Что это значит?

2022-04-03 08:00 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Eventnet.Api.csproj
> +
Тебе. Найди это правило и сохрани конфиг. Можешь выбрать любой вариант, главное, чтобы был один.

2022-04-03 08:01 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +        if (userNameExists is not null)
Протестую. Либо везде в if, либо вне. Ты уже начал осознавать, насколько уродливо пихать await в if...

2022-04-03 08:02 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +        if (user is null || !await userManager.CheckPasswordAsync(user, loginModel.Password))
Почему?

2022-04-03 08:02 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +        if (user is null || !await userManager.CheckPasswordAsync(user, loginModel.Password))
> По телефону - нет, телефон это прошлый век

Всегда по телефону захожу в вк...

2022-04-03 08:08 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +        if (user is null || !await userManager.CheckPasswordAsync(user, loginModel.Password))
> Почему?

Потому что нет такого метода у userManager

2022-04-03 08:09 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +        if (user is null || !await userManager.CheckPasswordAsync(user, loginModel.Password))
> > По телефону - нет, телефон это прошлый век
> 
> Всегда по телефону захожу в вк...

1) Вк - это прошлый век
2) У нас не совсем соц сеть (не понимаю ваще, для чего нужно давать входить по телефону, тогда нужно требовать его подтверждения, а это будет уже совсем.... Тип подтвердите почту, подтвердите номер, подтвердите подтвердите)

2022-04-03 08:09 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +        if (userNameExists is not null)
Протест отклонен

2022-04-03 08:09 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Eventnet.Api.csproj
> +
Чекну

2022-04-03 08:10 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Models/LocationFilterModel.cs
> +    double Radius);
так у меня по editorconfig, который лежит в корне форматирование идет...

2022-04-03 08:25 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +        if (userNameExists is not null)
Как и пулл реквест.

2022-04-03 08:25 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +        if (user is null || !await userManager.CheckPasswordAsync(user, loginModel.Password))
> > Почему?
> 
> Потому что нет такого метода у userManager

Как же ты слаб

2022-04-03 08:27 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +        if (user is null || !await userManager.CheckPasswordAsync(user, loginModel.Password))
KISS

2022-04-03 09:57 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Program.cs
> +services.AddScoped<IForgotPasswordService, ForgotPasswordService>();
в singleton сервис я не смогу инжектнуть scoped сервис
кажется, что singleton подразумевает, что у нас есть какое-то состояние

2022-04-03 11:37 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Eventnet.Api.csproj
> +
https://youtrack.jetbrains.com/issue/RIDER-40468

2022-04-03 11:39 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
> +        if (userNameExists is not null)
Метод возвращает не bool значение => логично, что его можно сложить в переменную
А если он возвращает bool, то можно это выполнить прямо в ифе

2022-04-04 15:48 UTC, IvanSibirtsev approved these changes

2022-04-05 04:00 UTC, gODeaLoAple approved these changes

2022-04-05 04:00 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
>          var user = await userManager.FindByNameAsync(loginModel.Login)
Кек, почему не LoginOrEmail?

2022-04-05 04:06 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
>          var user = await userManager.FindByNameAsync(loginModel.Login)
Потому что нет такого метода, как я уже и писал. 
Вводить его ради одного случая думаю не нужно

2022-04-05 04:15 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
>          var user = await userManager.FindByNameAsync(loginModel.Login)
Так у тебя по смыслу эта переменная содержит Login or Email. Я про переменную говорил, кста

2022-04-05 04:29 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
>          var user = await userManager.FindByNameAsync(loginModel.Login)
Login = username | email

2022-04-05 04:30 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Controllers/UserAccountController.cs
>          var user = await userManager.FindByNameAsync(loginModel.Login)
Имеет смысл

2022-04-08 16:57 UTC, merged