Users
HardSign-Team/eventnet-backend pull request #9
Opened 2022-04-10 17:01 UTC by DaGnYMilleR

2022-04-12 06:57 UTC, gODeaLoAple requested changes
Пока не увидел тестов.

2022-04-12 06:57 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Config/ApplicationMappingProfile.cs
> +                    x.MapFrom(opt => DateOnly.FromDateTime(opt.BirthDate)))
```suggestion
                x => x.MapFrom(opt => DateOnly.FromDateTime(opt.BirthDate)))
```

2022-04-12 06:57 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Program.cs
> +    x.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter()));
Я правильно понимаю, что ты будешь отправлять строку "Male" или "Female" из-за этого конвертера? Может, слать просто числа?

2022-04-12 06:57 UTC, gODeaLoAple commented on Eventnet/Eventnet.DataAccess/Models/Gender.cs
> +}
Почему Gender дублируется? Может, вынести это в инфру хотя бы? Либо удалить из Eventnet.Api.

2022-04-12 16:13 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Program.cs
> +    x.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter()));
По дефолту он шлет просто числа, да, но так кажется читаемей

2022-04-12 16:13 UTC, DaGnYMilleR commented on Eventnet/Eventnet.DataAccess/Models/Gender.cs
> +}
удалить из апи +

2022-04-12 16:14 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Config/ApplicationMappingProfile.cs
> +                    x.MapFrom(opt => DateOnly.FromDateTime(opt.BirthDate)))
Тебе на модельки тесты написать?

2022-04-12 20:47 UTC, gODeaLoAple commented on Eventnet/Eventnet.Api/Config/ApplicationMappingProfile.cs
> +                    x.MapFrom(opt => DateOnly.FromDateTime(opt.BirthDate)))
Внатуре. А старые тесты не учитывают новые данные у юзера?

2022-04-13 01:37 UTC, DaGnYMilleR commented on Eventnet/Eventnet.Api/Config/ApplicationMappingProfile.cs
> +                    x.MapFrom(opt => DateOnly.FromDateTime(opt.BirthDate)))
Вроде нет

2022-04-17 09:12 UTC, gODeaLoAple approved these changes

2022-04-17 11:54 UTC, IvanSibirtsev approved these changes

2022-04-17 17:21 UTC, merged